const std = @import("std");
const zine = @import("zine");

pub fn build(b: *std.Build) !void {
    zine.website(b, .{
        .title = "Gota7",
        .host_url = "https://gota7.com",
        .layouts_dir_path = "layouts",
        .content_dir_path = "content",
        .assets_dir_path = "assets",
        .static_assets = &.{
            "images/art/AuraColor.png",
            "images/art/AuraSketch.png",
            "images/art/BiscuitColor.png",
            "images/art/BiscuitSketch.png",
            "images/art/BoosterColor.png",
            "images/art/BoosterSketch.png",
            "images/art/Cyb3rShaded.png",
            "images/art/Cyb3rSketch.png",
            "images/art/DateShaded.png",
            "images/art/DateSketch.png",
            "images/art/EbonyShaded.png",
            "images/art/EbonySketch.png",
            "images/art/ElsaColor.png",
            "images/art/ElsaSketch.png",
            "images/art/ExelShaded.png",
            "images/art/ExelSketch.png",
            "images/art/IridescenceShaded.png",
            "images/art/IridescenceSketch.png",
            "images/art/JayShaded.png",
            "images/art/JaySketch.png",
            "images/art/LilianaShaded.png",
            "images/art/LilianaSketch.png",
            "images/art/MercurySketch.png",
            "images/art/MittensColor.png",
            "images/art/MittensSketch.png",
            "images/art/MochiColor.png",
            "images/art/MochiSketch.png",
            "images/art/RaijinColor.png",
            "images/art/RaijinSketch.png",
            "images/art/ShaymColor.png",
            "images/art/ShaymSketch.png",
            "images/art/VillagerShaded.png",
            "images/art/VillagerSketch.png",
            "images/gota/gotaCute.png",
            "images/home/gotaBlob.png",
            "images/music/TyeDieGota.png",
            "images/bg.png",
            "images/cursor.png",
            "images/favicon.ico",
            "images/titlebar.png",
            "images/titlebarClose.png",
            "images/titlebarMinimizeMaximize.png",
            "music/PerfectAngelsAcoustic.mp3",
        },
    });
}
